<h1>Python: without numpy or sklearn </h1>

In [1]:
import numpy as np
import pandas as pd

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [2]:
def matrix_mul(A,B):

    r=[]

    for i in range(len(A)):
        z=[]
        for j in range(len(B[0])):
            a=0 ; k=0
            for e in range(len(B)):
                k+= A[i][a]*B[e][j]
                a+=1
            z.append(k)
        r.append(z)
        
    return r

A   = [[1 ,2], [3, 4]]
B   = [[1, 2 ,3 ,4, 5], [5,6 ,7 ,8, 9]]

matrix_mul(A,B)

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [3]:
import random

def propotional_sampling(a):
    #cummulative
    A = [i/sum(a) for i in a]

    k=[]
    k.append(A[0])
    for i in range(1,len(A)):
        k.append(k[i-1]+A[i])
    
    r = random.random()
    for itr in range(len(k)) :
        if r < k[itr] :
            return a[itr]

a = [0 ,5, 27, 6, 13, 28, 100, 45 ,10 ,79]

sampled_elements = []
for itr in range(1000) :
    sampled_elements.append(propotional_sampling(a))
    
a=sorted(a)
for i in a:
    print('Number: {}, Frequency: {}'.format(i , sampled_elements.count(i)))

Number: 0, Frequency: 0
Number: 5, Frequency: 10
Number: 6, Frequency: 25
Number: 10, Frequency: 40
Number: 13, Frequency: 41
Number: 27, Frequency: 109
Number: 28, Frequency: 86
Number: 45, Frequency: 142
Number: 79, Frequency: 233
Number: 100, Frequency: 314


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [4]:
def replace_digits(String):
    output=''
    for i in String:
        if ord(i) > 47     and ord(i)< 58 :
            output+='#'
            
    return output


string='#2a$#b%c%561#'
replace_digits(string)


'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [5]:
import math

def display_dash_board(students, marks):
    sorted_=sorted(Marks)
    for i in range(-1,-6,-1):
        print(Students[i],'=', sorted_[i])
    print('-'*125)    
    for i in range(0,5,1):
         print(Students[i],'=', sorted_[i])
    print('-'*125)

    dict_=dict()
    c=0
    for i in Students:
        dict_[Marks[c]]=i
        c+=1
    
    for j in sorted(dict_):
        percentile =(j*100)/100
        if 25<percentile<75:
            print(dict_[j],'=', j)
            #print(sorted_)
            

        
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

display_dash_board(Students, Marks)

student10 = 98
student9 = 80
student8 = 78
student7 = 48
student6 = 47
-----------------------------------------------------------------------------------------------------------------------------
student1 = 12
student2 = 14
student3 = 22
student4 = 43
student5 = 45
-----------------------------------------------------------------------------------------------------------------------------
student6 = 43
student1 = 45
student7 = 47
student5 = 48


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [6]:
import math

def closest_points_to_p(S,P):
    o=[]
    for i in S:
        x=i[0]
        y=i[1]
        p=P[0]
        q=P[1]
        
        num=((x*p)+(y*q))
        den=np.sqrt((x**2)+(y**2)) * np.sqrt((p**2)+(q**2))
        r= num/den
        
        o.append((round(math.acos(r),3),i))
        
    o=sorted(o)
    for i in range(5):
        print(o[i][1])
        

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

closest_points_to_p(S,P)

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [7]:
import re

def i_am_the_one(Red,Blue,Lines):
    
    red = []
    blue= []
    final_red = []
    final_blue = []
    
    for line in Lines:
        a, b, c = [float(x.strip()) for x in re.split('x|y', line)]
        R=[]
        B=[]
        for i in range(len(Red)):
            r = ((a*Red[i][0])+(b*Red[i][1])+c)
            R.append(r)
        red.append(R)
        for _ in range(len(Blue)):
            z = ((a*Blue[_][0])+ (b*Blue[_][1])+ c)
            B.append(z)
        blue.append(B)
    
    for i in range(len(Lines)):
        Red=True
        Blue=True
        r=list(filter(lambda i: i>=0,red[i]))
        b=list(filter(lambda i: i<0, blue[i]))
    
        if len(r) == len(b) and len(r)==0 or len(r) == len(red[i]):
            print('YES')
        else:
            print('NO')
            
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

i_am_the_one(Red,Blue,Lines)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [8]:
def curve_smoothing(string):
#splitted given string by comma and saved it in varable s
    s="_,_,30,_,_,_,50,_,_".split(',')

    d=0
    for i in range(len(s)):
        c=False
        if s[i]!= '_' and s[d]!='_' and i!=0:
            k= (int(s[i])+int(s[d])) / ((i-d)+1)
            c=True
        elif s[i]!='_' and s[d]=='_':
            k = (int(s[i]))/((i-d)+1)
            c=True
        
        elif i==len(s)-1 and s[i]=='_':
            k= (int(s[d])) / ((i-d)+1)
            c=True

        if c:
            for j in range(d,i+1):
                s[j] = str(round(k))
            
            d=i
        
    return (',').join(s)

string= "_,_,30,_,_,_,50,_,_"

print(string)
curve_smoothing(string)

_,_,30,_,_,_,50,_,_


'10,10,12,12,12,12,4,4,4'

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [9]:
def compute_conditional_probabilites(A):
    dict_S=dict()
    dict_F=dict()
    for i in range(len(A)):
        if A[i][1] in dict_S:
            dict_S[A[i][1]] += 1
        else:
            dict_S[A[i][1]] = 1
        
    for i in range(len(A)):
        if A[i][0] in dict_F:
            dict_F[A[i][0]] += 1
        else:
            dict_F[A[i][0]] = 1
    c=dict()        
    for i in dict_S:
        for j in dict_F:
            r=False
            for k in range(len(A)):
                if [j,i] == A[k]:
                    if j+i in c:
                        c[j+i] +=1
                    else:
                        c[j+i] = 1
                        r=True
                    
            if r == False:
                c[j+i]=0
                    
                    
    print('P(F=F1|S==S1)=',c['F1S1'],'/',dict_S['S1'],', P(F=F1|S==S2)=', c['F1S2'],'/',dict_S['S2'],', P(F=F1|S==S3)=',c['F1S3'],'/',dict_S['S3'])
    print('P(F=F2|S==S1)=',c['F2S1'],'/',dict_S['S1'],', P(F=F2|S==S2)=', c['F2S2'],'/',dict_S['S2'],', P(F=F2|S==S3)=',c['F2S3'],'/',dict_S['S3'])
    print('P(F=F3|S==S1)=',c['F3S1'],'/',dict_S['S1'],', P(F=F3|S==S2)=', c['F3S2'],'/',dict_S['S2'],', P(F=F3|S==S3)=',c['F3S3'],'/',dict_S['S3'])
    print('P(F=F4|S==S1)=',c['F4S1'],'/',dict_S['S1'],', P(F=F4|S==S2)=', c['F4S2'],'/',dict_S['S2'],', P(F=F4|S==S3)=',c['F4S3'],'/',dict_S['S3'])
    print('P(F=F5|S==S1)=',c['F5S1'],'/',dict_S['S1'],', P(F=F5|S==S2)=', c['F5S2'],'/',dict_S['S2'],', P(F=F5|S==S3)=',c['F5S3'],'/',dict_S['S3'])
 

In [10]:
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)

P(F=F1|S==S1)= 1 / 4 , P(F=F1|S==S2)= 1 / 3 , P(F=F1|S==S3)= 0 / 3
P(F=F2|S==S1)= 1 / 4 , P(F=F2|S==S2)= 1 / 3 , P(F=F2|S==S3)= 1 / 3
P(F=F3|S==S1)= 0 / 4 , P(F=F3|S==S2)= 1 / 3 , P(F=F3|S==S3)= 1 / 3
P(F=F4|S==S1)= 1 / 4 , P(F=F4|S==S2)= 0 / 3 , P(F=F4|S==S3)= 1 / 3
P(F=F5|S==S1)= 1 / 4 , P(F=F5|S==S2)= 0 / 3 , P(F=F5|S==S3)= 0 / 3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [11]:
def string_features(S1, S2):
    S1=S1.split()
    S2=S2.split()
    count=0
    common_words=[]
    for i in range(len(S1)):
        if S1[i] not in common_words:
            for j in range(len(S2)):
                if S1[i]==S2[j] and S1[i]:
                    count+=1
                    common_words.append(S1[i])
    words_S1=[]
    for i in range(len(S1)):
        if S1[i] not in common_words:
            words_S1.append(S1[i])
            
    words_S2=[]
    for i in range(len(S2)):
        if S2[i] not in common_words:
            words_S2.append(S2[i])
            
    print('Number of common words: ', count)
    print('Words in S1 but not in S2 are: ',words_S1)
    print('Words in S2 but not in S1 are: ',words_S2)
    
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

string_features(S1, S2)
            

Number of common words:  7
Words in S1 but not in S2 are:  ['first', 'F', '5']
Words in S2 but not in S1 are:  ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [12]:
import math

def compute_log_loss(A):
    # n = number of rows in the matrix
    # creating a variable loss to sum the loss of each row
    n=len(A)
    loss=0
    for i in range(len(A)):
        y=A[i][0]
        y_score=A[i][1]
        loss += (y*math.log10(y_score)) + (1-y)* (math.log10(1-y_score))
    loss = round((-1/8)*loss,7)
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.4243099
